### ISSUE TITLE
Error in the code!!

### ISSUE THREAD

**Issue by SallamAltanna** [oliverjam/intro-react-workshop#5]
In the fourth section of the workshop, which is "Storm the Form", inside "Multiple inputs" part,
There is an error in the code. The code is inside the form tag.
 Line 20: `value={this.state.input}` should be replaced to be `value={this.state.name}`
Line 29: `value={this.state.input}` should be replaced to be `value={this.state.email}`

Hope this is clear and helpful!

**Comment by oliverjam** [comment]
Thanks for pointing that out! I'll push a fix now
